{{- if (merge (index .Values "bxfinanceapp")).ingress.enabled }}

{{- $v := index .Values "bxfinanceapp" -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ include "bx.name" . }}
    helm.sh/chart: {{ include "bx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations: {{ toYaml $v.ingress.annotations  | nindent 4 }}
  name: bxfinance-{{ .Release.Name }}-client-ingress
spec:
  rules:
  - host: {{ .Values.bxfinanceapp.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingaccess-engine
            port:
              number: {{ ( index .Values "ping-devops" "pingaccess-engine" ).services.https.servicePort }}
  tls:
  - hosts:
      - {{ .Values.bxfinanceapp.ingress.host }}
    secretName: {{ .Values.bxfinanceapp.ingress.tlsSecret }}
{{- end -}}