bxhealthapp:
  enabled: false
  name: bxhealthapp
  image:
    repository: gcr.io/ping-gte
    name: bxhealthapp-dev
    tag: latest
    pullSecret: ""
  envs:
    SERVER_PROFILE_URL: ""
    STARTUP_COMMAND: "tail"
    STARTUP_BACKGROUND_OPTS: "-f /dev/null"
  ingress:
    host: bxhealth.ping-devops.com
    pingaccess:
  workload:
    deployment:
      strategy:
        type: Recreate
  container:
    resources:
      requests:
        cpu: 0
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 1Gi
    probes:
      livenessProbe:
        exec:
          command:
            - echo
      readinessProbe:
        exec:
          command:
            - echo
      startupProbe:
        exec:
          command:
            - echo


ping-devops:
  global: 
    ingress:
      enabled: false
      addReleaseNameToHost: append
      defaultDomain: ping-devops.com
      defaultTlsSecret:
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        kubernetes.io/ingress.class: "nginx-public"
  pingaccess-admin:
    enabled: true
    privateCert:
      generate: true
    workload:
      type: Deployment
      deployment:
        strategy:
          type: Recreate
    container:
      waitFor:
        pingfederate-engine:
          service: https
          timeoutSeconds: 600
      resources:
        requests:
          cpu: 0
          memory: 1.5Gi
        limits:
          cpu: 1500m
          memory: 1.5Gi
    envs:
      SERVER_PROFILE_URL: https://github.com/Technical-Enablement-PingIdentity/BXHealth-ServerProfiles
      SERVER_PROFILE_PATH: profiles/pingaccess
    services:
      http:
        servicePort: 8080
        containerPort: 8080
        ingressPort: 80
        dataService: true

  pingaccess-engine:
    enabled: true
    workload:
      type: Deployment
      deployment:
        strategy:
          type: Recreate
    container:
      replicaCount: 1
      resources:
        requests:
          cpu: 0
          memory: 1.5Gi
        limits:
          cpu: 1500m
          memory: 1.5Gi
    envs:
      SERVER_PROFILE_URL: https://github.com/Technical-Enablement-PingIdentity/BXHealth-ServerProfiles
      SERVER_PROFILE_PATH: profiles/pingaccess

  pingfederate-admin:
    enabled: true
    container:
      waitFor:
        pingdirectory:
          service: ldaps
          timeoutSeconds: 300
      resources:
        requests:
          cpu: 0
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi
    envs:
      SERVER_PROFILE_URL: https://github.com/Technical-Enablement-PingIdentity/BXHealth-ServerProfiles
      SERVER_PROFILE_PATH: profiles/pingfederate
  
  pingfederate-engine:
    enabled: true
    container:
      resources:
        requests:
          cpu: 0
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi
    envs:
      SERVER_PROFILE_URL: https://github.com/Technical-Enablement-PingIdentity/BXHealth-ServerProfiles
      SERVER_PROFILE_PATH: profiles/pingfederate

  pingdirectory:
    enabled: true
    container:
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 3Gi
        limits:
          cpu: 2
          memory: 3Gi
    envs:
      SERVER_PROFILE_URL: https://github.com/Technical-Enablement-PingIdentity/BXHealth-ServerProfiles
      SERVER_PROFILE_PATH: profiles/pingdirectory
      MAX_HEAP_SIZE: 2458m
      ROOT_USER_PASSWORD_FILE: /opt/staging/pwd
      ADMIN_USER_PASSWORD_FILE: /opt/staging/pwd
      ENCRYPTION_PASSWORD_FILE: /opt/staging/pwd
    services:
      ldap:
        servicePort: 389
        containerPort: 1389
        dataService: true
      ldaps:
        servicePort: 636
        containerPort: 1636
        dataService: true
        clusterService: true
      https:
        servicePort: 443
        containerPort: 1443
        ingressPort: 443
        dataService: true
  
  pingdataconsole:
    enabled: true
    #TODO: GDO-1020
    envs:
      SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
      SERVER_PROFILE_PATH: baseline/pingdataconsole
      SERVER_PROFILE_BRANCH: master
  
  pingauthorize:
    enabled: true
    container:
      waitFor:
        pingdirectory:
          service: ldaps
          timeoutSeconds: 300
    envs:
      SERVER_PROFILE_URL: https://github.com/Technical-Enablement-PingIdentity/BXHealth-ServerProfiles
      SERVER_PROFILE_PATH: profiles/pingauthorize
      ROOT_USER_PASSWORD_FILE: /opt/staging/pwd
      ADMIN_USER_PASSWORD_FILE: /opt/staging/pwd
      ENCRYPTION_PASSWORD_FILE: /opt/staging/pwd

  pingauthorizepap:
    enabled: true
    envs:
      SERVER_PROFILE_URL: https://github.com/Technical-Enablement-PingIdentity/BXHealth-ServerProfiles
      SERVER_PROFILE_PATH: profiles/pingauthorizepap
    container:
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 1.5Gi
        limits:
          cpu: 2
          memory: 1.5Gi
