bxhealthapp:
  enabled: true
  name: bxhealthapp
  image:
    repository: pingidentity
    name: pingtoolkit
    tag: "2108"
  envs:
    SERVER_PROFILE_URL: ""
    STARTUP_COMMAND: "tail"
    STARTUP_BACKGROUND_OPTS: "-f /dev/null"

ping-devops: {}

## COPIED GLOBAL FROM ping-devops 0.7.6
global:
  ############################################################
  # annotations - Annotations listed, will be added to the
  #               kubernetes resource
  ############################################################
  annotations: {}

  ############################################################
  # envs - Environment variables listed will be added to the
  #        global-env-vars configmap.
  #
  # NOTE: Environment variables listed at the global: level
  #       will actually end up being listed twice in the
  #       configmaps (i.e. global-env-vars and product-env-vars)
  ############################################################
  envs: {}

  ############################################################
  #  addReleaseNameToResource: Provides global ability to add
  #                            names to kubernetes resources
  #                      none: No use of Release.Name
  #                    append: Appends the Release.Name
  #                   prepend: Prepends the Release.Name ** DEFAULT **
  ############################################################
  addReleaseNameToResource: prepend

  ############################################################
  # Ingress
  #
  #          ingress.enabled: {true | false}
  # ingress.addReleaseToHost: {prepend | append | subdomain | none}
  #    ingress.defaultDomain: Replaces with "_defaultDomain_" in host fields
  # ingress.defaultTlsSecret: Replaces with "_defaultTlsSecret_" in tls.secretName
  ############################################################
  ingress:
    enabled: false
    addReleaseNameToHost: subdomain
    defaultDomain: example.com
    defaultTlsSecret:
    annotations: {}
      # nginx example
      # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # kubernetes.io/ingress.class: "nginx-public"

  ############################################################
  # Internal Certificates
  #
  # If set to true, then an internal certificate secret will
  # be created along with mount of the certificate in
  # /run/secrets/internal-cert (creates a tls.crt and tls.key)
  #
  # By default the Issuer of the cert will be the service name
  # created by the Helm Chart.  Additionally, the ingress hosts,
  # if enabled, will be added to the list of X509v3 Subject Alternative Name
  #
  # Use the additionalHosts and additionalIPs if additional custom
  # names and ips are needed.
  #
  #      privateCert.generate: {true | false}
  #      privateCert.additionalHosts: {optional array of hosts}
  #      privateCert.additionalIPs: {optional array of IP Addresses}
  ############################################################
  privateCert:
    generate: false
    additionalHosts: []
    additionalIPs: []

  ############################################################
  # Fields used to annotate secret hashicorp vault information
  #
  # These annotations names will be automatically be
  # appended to the 'vault.hashicorp.com/'
  #
  # https://www.vaultproject.io/docs/platform/k8s/injector/annotations
  ############################################################
  vault:
    enabled: false
    hashicorp:
      annotations:
        agent-inject: true
        agent-init-first: true
        agent-pre-populate-only: true
        log-level: info
        preserve-secret-case: true
        role: k8s-default
        secret-volume-path: /run/secrets
        serviceAccountName: vault-auth
  #   secrets:
  #     {secret-name}:
  #       {secret-key | to-json}:
  #         path: /opt/in/some/location/secrets
  #         file: devops-secret.env

  ############################################################
  # Image
  #
  # By default the images uses will be indicated by these
  # variables.  An example might look like:
  #
  #   pingidentity/pingdataconsole:2108 (August, 2021)
  #
  # NOTE: image.name MUST be set in child chart
  #   Example: image.name: pingfederate
  ############################################################
  image:
    repository: pingidentity
    name:
    tag: "2108"
    pullPolicy: IfNotPresent

  ############################################################
  # External Images (typically for initContainers)
  #
  # Provides ability to use external images for various purposes
  # such as using curl, waitfor, ...  Example below is for use
  # of the pingtoolkit image used as a waitFor and generation of
  # private cert initContainers.
  #
  # Values found within each external image are copied directly
  # to the container/initContainer.
  ############################################################
  externalImage:
    pingtoolkit:
      image: pingidentity/pingtoolkit:2108
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 1m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 9031
        runAsGroup: 9999

  ############################################################
  # Services
  #
  # Creates services mapping a port to a targetPort on the
  # corresponding container.
  #
  # dataService    - If set to true, a ClusterIP service is
  #                  created reachable within the cluster.
  #                  A single IP is provided and the service
  #                  will round-robin across the backend containers.
  #
  # clusterService - If set to true, a "headless" service is
  #                  explicitly specifying "None" for the
  #                  clusterIP.  DNS requests to this service
  #                  will provide one of the IPs of the backend
  #                  containers.
  #
  # containerPort  - Port that is used on the kubernetes container.
  #
  # servicePort    - Port that is available from the kubernetes service
  #                  Note: if clusterService=true this port on the
  #                        cluster service is not really
  #                        used as headless service always maps through
  #                        to the container port
  #
  # ingressPort    - Port that is available from the kubernetes ingress
  #
  # clusterServiceName - If set, then this name will be used as the cluster
  #                      service name (i.e clusterService == true).
  #
  # https://kubernetes.io/docs/concepts/services-networking/service/
  ############################################################
  services: {}
  #  admin:
  #    containerPort: 9999
  #    servicePort: 9999
  #    ingressPort: 9999
  #    dataService: true
  #  clusterbind:
  #    containerPort: 7600
  #    servicePort: 7600
  #    clusterService: true
  #  clusterfail:
  #    containerPort: 7700
  #    servicePort: 7700
  #    clusterService: true
  #  clusterExternalDNSHostname:
  #  clusterServiceName:


  ############################################################
  # Workload
  #
  # Two workloads supported:
  #  - Deployment
  #  - StatefulSet
  ############################################################
  workload:
    # Can be Deployment or StatefulSet
    type: Deployment

    annotations: {}

    ############################################################
    # schedulerName
    #
    # Provide the kubernetes default-scheduler, and allow for override
    #
    # https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/
    ############################################################
    schedulerName: default-scheduler

    ############################################################
    # Deployments
    #
    # Detailed information used to create a deployment specific
    # workload.
    #
    # https://kubernetes.io/docs/concepts/workloads/controllers/deployment
    ############################################################
    deployment:
      strategy:
        # Can be RollingUpdate or Recreate
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

    ############################################################
    # StatefulSets
    #
    # Detailed information used to create a statefulSet specific
    # workload.
    #
    # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset
    ############################################################
    statefulSet:
      # Used for canary testing if n>0
      partition: 0

      ############################################################
      # Persistent Volumes
      #
      # For every volume defined in the volumes list, 3 items will be
      # created in the StatefulSet
      #   1. container.volumeMounts - name and mountPath
      #   2. template.spec.volume - name and persistentVolumeClaim.claimName
      #   3. spec.volumeClaimTemplates - persistentVolumeClaim
      #
      # https://kubernetes.io/docs/concepts/storage/persistent-volumes/
      ############################################################
      persistentvolume:
        enabled: true
        volumes:
          out-dir:
            mountPath: /opt/out
            persistentVolumeClaim:
              accessModes:
              - ReadWriteOnce
              storageClassName:
              resources:
                requests:
                  storage: 4Gi

    ############################################################
    # securityContext
    #
    # Note: The user (9031) and group (9999) represent the current user
    #       and group used with PingIdentity images (except PingDelegator).
    #       The fsGroup is set to same as group, however, it can be set to
    #       any gid number.
    #       The fsGroup is required for any workloads that volumeMount
    #       a pvc (i.e. StatefulSets)
    ############################################################
    securityContext:
      fsGroup: 9999
      runAsUser: 9031
      runAsGroup: 9999
      # allowPrivilegeEscalation: false
      # capabilities:
      #   drop:
      #   - ALL

  ############################################################
  # Container Information
  #
  # https://kubernetes.io/docs/concepts/workloads/controllers/
  ############################################################
  container:
    # replicaCount - Instructs Deployment/StatefulSet now many containers to run
    replicaCount: 1

    # resources - Request  0 cpu/0 GB
    #             Limit    4 cpu/0 GB
    resources:
      requests:
        cpu: 0
        memory: 0
      limits:
        cpu: 0
        memory: 0
    nodeSelector: {}
    tolerations: []
    affinity: {}
    terminationGracePeriodSeconds: 30

    envFrom: []
    # Additional envFrom configmap/secret references can be added
    # envFrom:
    # - configMapRef:
    #     name: my-example-configmap
    #     optional: true
    # - secretRef:
    #     name: my-example-secrets
    #     optional: true

    ############################################################
    # container life handlers, allowing for lifecycle events such
    # as postStart and preStop events
    #
    # https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event
    ############################################################
    lifecycle: {}
    # Example
    # lifecycle:
    #   postStart:
    #     exec:
    #       command: ["/bin/sh", "-c", "echo Start Complete > /tmp/message"]

    ############################################################
    # Probes
    #
    # Probes have a number of fields that you can use to more precisely control the
    # behavior of liveness and readiness checks.
    #
    # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
    ############################################################
    probes:
      livenessProbe:
        exec:
          command:
            - /opt/liveness.sh
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 4
      readinessProbe:
        exec:
          command:
            - /opt/readiness.sh
        initialDelaySeconds: 30
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 4
      startupProbe:
        exec:
          command:
            - /opt/liveness.sh
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 90

  ############################################################
  # Licensing
  #
  # license.secret.devOps
  #    Identify the k8s secret to keep the DevOps USER/KEY if used during deployment.
  #
  # NOTE: licenseSecretName can be set in deploying chart values to specify a secret
  #       with actual product license.  This would override the DevOps secret.
  #
  # Using pingctl utility (brew install pingctl):
  #    pingctl k8s generate devops-secret | kubectl apply -f -
  ############################################################
  license:
    secret:
      devOps: devops-secret

  #############################################################
  # Includes for sidecars, initContainers and volumes
  #
  # At both global and product level, includes of sidecars,
  # initContainers and volumes can be provided.  By default,
  # none are included.
  #############################################################
  includeSidecars: []
  includeInitContainers: []
  includeVolumes: []