{{- if (merge (index .Values "bxapi") ).ingress.enabled }}

{{- $v := index .Values "bxapi" -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ include "bx.name" . }}
    helm.sh/chart: {{ include "bx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations: {{ toYaml $v.ingress.annotations  | nindent 4 }}
  name: {{ .Release.Name }}-api-ingress
spec:
  rules:
  - host: {{ .Values.bxapi.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-bxapi
            port:
              number: {{ .Values.bxapi.services.https.servicePort }}
{{- if .Values.bxapi.ingress.alias }} 
  - host: {{ .Values.bxapi.ingress.alias }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-bxapi
            port:
              number: {{ .Values.bxapi.services.https.servicePort }}
{{- end }}
  tls:
  - hosts:
      - {{ .Values.bxapi.ingress.host }}
    secretName: {{ .Values.bxapi.ingress.tlsSecret }}
{{- end -}}