{{- range (list "bxapi" ) }}
    {{- if (merge (index $.Values . ) $.Values.global).privateCert.generate }}
        {{- include "pinglib.private-cert" (list $ .) }}
---
    {{- end }}
{{- end }}


{{- define "bxapi.private-cert" -}}{{- end -}}