apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ include "bx.name" . }}
    helm.sh/chart: {{ include "bx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    # nginx.ingress.kubernetes.io/service-upstream: "true"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: bxhealth-{{ .Release.Name }}-client-ingress
spec:
  rules:
  - host: {{ .Values.bxhealthapp.ingress.host }}
    http:
      paths:
      - path: /
        #pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-pingaccess-engine
          servicePort: {{ ( index .Values "ping-devops" "pingaccess-engine" ).services.https.servicePort }}
      - path: /.well-known/acme-challenge
        #pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-pingaccess-engine
          servicePort: {{ ( index .Values "ping-devops" "pingaccess-engine" ).services.http.servicePort }}