{{- if (merge (index .Values "bxhealthapp")).ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ include "bx.name" . }}
    helm.sh/chart: {{ include "bx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/app-root: /app/
  name: bxhealth-{{ .Release.Name }}-client-ingress
spec:
  rules:
  - host: {{ .Values.bxhealthapp.ingress.host }}
    http:
      paths:
      - path: /
        #pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-pingaccess-engine
          servicePort: {{ ( index .Values "ping-devops" "pingaccess-engine" ).services.https.servicePort }}
  tls:
  - hosts:
      - {{ .Values.bxhealthapp.ingress.host }}
    secretName: {{ .Values.bxhealthapp.ingress.tlsSecret }}
{{- end -}}