{{- range (list "bxhealthapp" ) }}
    {{- if (merge (index $.Values . ) $.Values.global).privateCert.generate }}
        {{- include "pinglib.private-cert" (list $ .) }}
---
    {{- end }}
{{- end }}


{{- define "bxhealthapp.private-cert" -}}{{- end -}}