{{- if (merge (index .Values "bxretailapp") ).ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ include "bx.name" . }}
    helm.sh/chart: {{ include "bx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/app-root: /app/
  name: bxretail-{{ .Release.Name }}-client-ingress
spec:
  rules:
  - host: {{ .Values.bxretailapp.ingress.host }}
    http:
      paths:
      - path: /
        #pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-bxretailapp
          servicePort: {{ .Values.bxretailapp.services.https.servicePort }}
  tls:
  - hosts:
      - {{ .Values.bxretailapp.ingress.host }}
    secretName: {{ .Values.bxretailapp.ingress.tlsSecret }}
{{- end -}}